services:
  etcd:
    image: bitnami/etcd:3.6.0
    ports:
      - 2379:2379
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      - ETCD_ROOT_PASSWORD=smartasset
      - ETCD_NAME=etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380

volumes:
  etcd_data: